### ISSUE TITLE
/etc/profile.d/plenv.sh ownership conflicts

### ISSUE THREAD

**Issue by christopherraa** [dmanto/ansible-plenv-and-carton#8]
If you activate plenv for multiple users on a system then Ansible will happily flip ownership of the file `/etc/profile.d/plenv.sh` between each of the users you have activated Plenv for. This strikes me as not being the best solution. I propose that this files is owned by root, but set executable for anyone.

**Comment by dmanto** [comment]
Ok, didn't actually try using more than a plenv user in same system, but don't see any problems this way
